from PyQt5 import QtCore, QtGui, QtWidgets
import basic

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 853)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 540, 61, 41))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 90, 541, 411))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_7.addWidget(self.label_22)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.xuanzetishuliang_5 = QtWidgets.QSpinBox(self.widget)
        self.xuanzetishuliang_5.setObjectName("xuanzetishuliang_5")
        self.horizontalLayout_5.addWidget(self.xuanzetishuliang_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_6.addWidget(self.label_23)
        self.xuanzetishuliang_6 = QtWidgets.QSpinBox(self.widget)
        self.xuanzetishuliang_6.setObjectName("xuanzetishuliang_6")
        self.horizontalLayout_6.addWidget(self.xuanzetishuliang_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.xuanzetishuliang = QtWidgets.QSpinBox(self.widget)
        self.xuanzetishuliang.setObjectName("xuanzetishuliang")
        self.horizontalLayout_3.addWidget(self.xuanzetishuliang)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.xuanzetifenshu = QtWidgets.QSpinBox(self.widget)
        self.xuanzetifenshu.setObjectName("xuanzetifenshu")
        self.horizontalLayout_3.addWidget(self.xuanzetifenshu)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.xuanzetishuliang_2 = QtWidgets.QSpinBox(self.widget)
        self.xuanzetishuliang_2.setObjectName("xuanzetishuliang_2")
        self.horizontalLayout_2.addWidget(self.xuanzetishuliang_2)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.xuanzetifenshu_2 = QtWidgets.QSpinBox(self.widget)
        self.xuanzetifenshu_2.setObjectName("xuanzetifenshu_2")
        self.horizontalLayout_2.addWidget(self.xuanzetifenshu_2)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.xuanzetishuliang_4 = QtWidgets.QSpinBox(self.widget)
        self.xuanzetishuliang_4.setObjectName("xuanzetishuliang_4")
        self.horizontalLayout_4.addWidget(self.xuanzetishuliang_4)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.xuanzetifenshu_4 = QtWidgets.QSpinBox(self.widget)
        self.xuanzetifenshu_4.setObjectName("xuanzetifenshu_4")
        self.horizontalLayout_4.addWidget(self.xuanzetifenshu_4)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.xuanzetishuliang_3 = QtWidgets.QSpinBox(self.widget)
        self.xuanzetishuliang_3.setObjectName("xuanzetishuliang_3")
        self.horizontalLayout.addWidget(self.xuanzetishuliang_3)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.xuanzetifenshu_3 = QtWidgets.QSpinBox(self.widget)
        self.xuanzetifenshu_3.setObjectName("xuanzetifenshu_3")
        self.horizontalLayout.addWidget(self.xuanzetifenshu_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.chioc)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "生成"))
        self.label_22.setText(_translate("MainWindow", "测试名称"))
        self.label.setText(_translate("MainWindow", "试卷份数"))
        self.label_23.setText(_translate("MainWindow", "起始学号"))
        self.label_12.setText(_translate("MainWindow", "题型"))
        self.label_13.setText(_translate("MainWindow", "选择题"))
        self.label_14.setText(_translate("MainWindow", "题"))
        self.label_15.setText(_translate("MainWindow", "每题"))
        self.label_16.setText(_translate("MainWindow", "分"))
        self.label_7.setText(_translate("MainWindow", "题型"))
        self.label_8.setText(_translate("MainWindow", "填空题"))
        self.label_9.setText(_translate("MainWindow", "题"))
        self.label_10.setText(_translate("MainWindow", "每题"))
        self.label_11.setText(_translate("MainWindow", "分"))
        self.label_17.setText(_translate("MainWindow", "题型"))
        self.label_18.setText(_translate("MainWindow", "计算题"))
        self.label_19.setText(_translate("MainWindow", "题"))
        self.label_20.setText(_translate("MainWindow", "每题"))
        self.label_21.setText(_translate("MainWindow", "分"))
        self.label_6.setText(_translate("MainWindow", "题型"))
        self.label_2.setText(_translate("MainWindow", "解答题"))
        self.label_3.setText(_translate("MainWindow", "题"))
        self.label_5.setText(_translate("MainWindow", "每题"))
        self.label_4.setText(_translate("MainWindow", "分"))

    def chioc(self):
        choice_num = self.xuanzetishuliang.value()
        choice_each_score = self.xuanzetifenshu.value()
        basic.choic(choice_num,choice_each_score)